# Generated by Django 5.1.7 on 2025-04-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0004_alter_usercity_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCity',
        ),
    ]
