# Generated by Django 5.1.7 on 2025-04-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0007_usercity'),
    ]

    operations = [
    ]
