# Generated by Django 5.2.1 on 2025-05-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0009_favouritecity_delete_usercity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritecity',
            name='city',
        ),
        migrations.AddField(
            model_name='favouritecity',
            name='city1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favouritecity',
            name='city2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favouritecity',
            name='city3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favouritecity',
            name='city4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
