# Generated by Django 5.2.1 on 2025-05-10 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0010_remove_favouritecity_city_favouritecity_city1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.CharField(blank=True, max_length=100, null=True)),
                ('city2', models.CharField(blank=True, max_length=100, null=True)),
                ('city3', models.CharField(blank=True, max_length=100, null=True)),
                ('city4', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FavouriteCity',
        ),
    ]
