# Generated by Django 5.2.1 on 2025-05-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0012_favouritecity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteCity',
        ),
    ]
