# Generated by Django 5.2.1 on 2025-05-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0013_delete_favouritecity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercities',
            name='last_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
