# Generated by Django 5.1.7 on 2025-05-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0015_userlastlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercities',
            name='last_location',
        ),
    ]
