# Generated by Django 5.1.7 on 2025-05-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0017_locationpictures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationPictures',
        ),
    ]
